#
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
---
application:
  server:
    port: ${MOCKSERVER_PORT:1080}
server:
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
spring:
  application:
    name: kotlin-mockserver
  banner:
    charset: UTF-8
  datasource:
    driver-class-name: org.h2.Driver
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:mock_server_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop     # ...uses import.sql
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  lifecycle:
    timeout-per-shutdown-phase: 60s
  main:
    banner-mode: "off"
    lazy-initialization: true
  mandatory-file-encoding: UTF-8
  output:
    ansi:
      enabled: detect
  profiles:
    active: default
---
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  main:
    banner-mode: console
    lazy-initialization: false
  profiles: sandbox
---
spring:
  profiles: test
